ls1intum/artemis-ansible-collection

roles/proxy/defaults/main.yml
roles/proxy/templates/nginx_timeouts.conf.j2

A longer timeout might be needed to support the repository export of large courses.
See https://github.com/ls1intum/Artemis/issues/4454 for details.

Make nginx timeouts configurable

---

roles/mysqld_exporter/README.md
roles/mysqld_exporter/defaults/main.yml
roles/mysqld_exporter/meta/requirements.yml
roles/mysqld_exporter/tasks/main.yml

Add prometheus mysqld_exporter role.
Uses exisiting role https://github.com/cloudalchemy/ansible-mysqld_exporter for deploying the exporter.
Additionally to deploying the mysql exporter, the mysql database user for srcaping the metrics is created.

Add mysqld_exporter role

---

roles/artemis/defaults/main.yml
roles/artemis/templates/application-prod.yml.j2

As https://github.com/ls1intum/Artemis/pull/4768 got merged, we need to add the bcrypt rounds to the config.

Add bcrypt rounds to config

---

roles/proxy/templates/nginx_artemis.conf.j2

Prevent bursts from being sent directly, but delay them to fit the requested rate.
Decrease the request rate on this endpoint

Improve authentication protection

---

roles/storage_client/templates/mnt-storage.mount.j2

Since the last cluster network refactoring the NFS share also is exposed in the wireguard network. However, the mount still depended on the general network target, not the wg interface. This caused the mount to fail during boot. With this change, systems waits until the wg network is up and running before mounting the NFS share

Add client mount dependency on wireguard interface

---

roles/proxy/files/nginx_502.html

We got the request that the 502-error page should reload itself (e.g. after 5 seconds) for developers on the test servers, but I would argue that this change also makes sense in the production environment

Reload 502-error page after 5 seconds.

---

roles/proxy/templates/nginx_artemis.conf.j2

@manuelmanso is working on the LTI-integration for which large (around 3kb) tokens are sent via Response Headers.
nginx currently does not support these large headers (a limit of 4kb for all headers seems to apply), so we have to increase the buffer size.
The limit of the buffer can still be discussed. Also, I'm not sure why the request is buffered at all, since `proxy_buffering` is set to `off` (EDIT: See this blog post: https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#proxy_buffering-off)

Increase proxy buffering.

---

roles/broker/defaults/main.yml
roles/broker/tasks/configure.yml

See "Options" at https://activemq.apache.org/components/artemis/documentation/latest/using-server.html:
```
--java-options <javaOptions>
Extra java options to be passed to the profile
```
This adds a variable (`activemq_system_ram_proportion`) to set the memory usage to a proportional amount of the available memory.
It also adds an option to force the re-installation of the broker(`activemq_force_reinstall`).
Testing steps:
1. Install the broker using ansible
2. Execute this command: `cat /opt/broker/etc/artemis.profile | grep "Xmx" . -r`
3. The output should be similar to the output here (Notice the Xms and Xmx arguments in the end):
```sleiss@ubunut-home-vm:/opt/broker/etc$ cat /opt/broker/etc/artemis.profile | grep "Xmx" . -r
./artemis.profile:    JAVA_ARGS="-XX:AutoBoxCacheMax=20000 …
```

Specify broker max memory

---

roles/artemis/defaults/main.yml
roles/artemis/templates/application-prod.yml.j2

Currently, the appliction.yml template is hardcoded to use MySQL. 
Since Artemis will soon support at least PostgreSQL, this has to be configurable, so we can set up a new test server.
For this, I added 4 new variables to specify the database types for JDBC and JPA and added them to the template. The default values for these are the previously hardcoded values or the default values from the Artemis repository.
Supporting PostgreSQL is now as trivial by setting the new values to:
```
artemis_database_schema: postgresql
artemis_database_type: POSTGRESQL
artemis_database_platform: org.hibernate.dialect.PostgreSQL10Dialect
artemis_database_port: 5432
```

Add support for databases other than MySQL

---

roles/artemis/defaults/main.yml
roles/artemis/templates/application-prod.yml.j2
roles/artemis/templates/artemis.env.j2
roles/artemis/templates/docker.env.j2

These PRs
https://github.com/ls1intum/Artemis/pull/6500
https://github.com/ls1intum/Artemis/pull/6670 introduce the following properties:
| Property | Value |Comment|
|----------|-------|------------|
|artemis.data-export-path| opt/artemis/data-export| not really sure if this is correct, I just used the legal-path property as a template
|artemis.data-export-days-between-data-exports |  14 |
|artemis.scheduling.programming-exercises-cleanup-time | 0 0 3 * * * |Cron expression
|artemis.scheduling.data-export-creation-time| 0 0 4 * * *|Cron expression

Add properties introduced for the data export 

---

roles/artemis/templates/application-prod.yml.j2
roles/artemis/templates/artemis.env.j2

There was an issue where the `ssh-private-key-folder-path` was not excluded for Gitlab setups when the `artemis_ssh_key_path` was empty. This broke communication with Gitlab, as Artemis tried to use non-existent ssh keys for authentication.
This PR adds the same if check that was already used for BitBucket setups to the Gitlab setup.

`Bugfix`: Fix empty ssh key path property for Gitlab

---

roles/proxy/defaults/main.yml
roles/proxy/templates/nginx_artemis.conf.j2

Related PR: https://github.com/ls1intum/Artemis/pull/6764
The linked PR removes an unused tracking functionality of Athene. This tracking needed its own Nginx endpoint, which this PR now removes from the ansible configuration.
**Update:** We also removed the `/athene-result` endpoint (which previously increased the max upload size) because the increased limit will not be necessary for future working versions, and there is no current working version of Athene anyways.

Remove special Athene endpoints

---

roles/artemis/templates/application-prod.yml.j2
roles/artemis/templates/artemis.env.j2

https://github.com/ls1intum/Artemis/pull/6861 was recently merged. 
Among other things, it changes the name of the secret for the communication with Athena from `base64-secret` to `secret` to reflect that it does not have to be base64-encoded.
I also removed the `token-validity-in-seconds` parameter because it's not used anywhere. [According to @jpbernius](https://github.com/ls1intum/Artemis/pull/6861#discussion_r1279733364), it was previously used for tracking functionality for research purposes.

Update Athena configuration to use only a secret

---

roles/artemis/README.md
roles/artemis/defaults/main.yml
roles/artemis/templates/application-prod.yml.j2

This PR introduces new Athena configuration for modules:
https://github.com/ls1intum/Artemis/pull/7136
This PR introduces the same configuration in Ansible as well.
The configuration is used to choose the assessment module used to generate Athena feedback suggestions. There are multiple approaches available. The configuration entry allows admins to choose which suggestion generation approach Athena takes.

Add Athena config for chosen modules

---

roles/artemis/tasks/docker_deploy_artemis.yml

The Postgres docker container needs special user permissions.
Currently, they are overwritten with the Artemis user permissions. As a result, Postgres fails to start.

`Development`: Fix user permissions for Postgres in docker setup

---

roles/artemis/templates/artemis-docker.sh.j2
roles/artemis/templates/docker.env.j2

For a simple and straightforward deployment `is_multinode_install` and `broker` is unset.
`broker` should only be used, if `is_multinode_install` is set.
If `is_multinode_install` is set to `false` it should not include the multi-node information. So it is not sufficient to check if the value is defined.

`Development`: Fix usage of multi-node variable if unset

---

roles/artemis/README.md
roles/artemis/templates/application-prod.yml.j2

This Artemis PR changes the Athena configuration for modules:
https://github.com/ls1intum/Artemis/pull/7809
This PR adapts the same configuration in Ansible as well.
With the restricted modules options, Athena feedback suggestion modules (e.g. modules that cost money per usage such as LLM Modules) can be made available only to courses that are allowed to access them.

Adapt Athena config and readme to latest changes allowing an individual module selection per exercise

---

roles/artemis/templates/artemis.service.j2

Simply set `hazelcast.slow.operation.detector.stacktrace.logging.enabled` to true in the service file

Enable Hazelcast slow operator logging

---

roles/artemis/tasks/node_checks.yml

The execution should fail if docker is _not_ installed.

`Bugix`: Fix fail condition when docker is not installed

---

roles/artemis/templates/application-prod.yml.j2
roles/artemis/templates/artemis.env.j2

This setting was changed with the Spring Boot 3 update in Artemis 7.0.0, so we need to update it here as well.

`Artemis`: Update prometheus metrics setting to match Artemis

---

roles/artemis/defaults/main.yml
roles/artemis/templates/application-prod.yml.j2
roles/artemis/templates/artemis.service.j2

Artemis 7.0.0 requires JDK21 to run. This PR switches the default version from 17 to 21.
I also did some smaller fixes for build agents nodes, as these do not require that much config to be present

`Artemis`: Switch to JDK 21

---

roles/artemis/defaults/main.yml
roles/artemis/templates/application-prod.yml.j2
roles/artemis/templates/artemis.env.j2

This PR implements changes requested by the ITG in [this issue](https://jira.ase.in.tum.de/browse/LS1ADMIN-38042).
Currently, the ongoing integration of Theia into Artemis requires some new configuration values. This PR adds the `theia_base_url` to prod and env templates and the defaults. 
@Hialus are the changes in `artemis.env.j2` sufficient or are there other changes necessary in some, e.g., Dockerfile?

`Development`: Add Theia configuration

---

roles/artemis/defaults/main.yml
roles/artemis/tasks/artemis_configuration.yml
roles/artemis/tasks/docker_deploy_artemis.yml

We have `artemis_ssh_key_path` set to `/tmp`. Setting the file permissions for `/tmp` results in problems.
Also `artemis_ssh_priv_key_value` is not needed anymore.

Fix file permissions for `artemis_ssh_key_path`

---

roles/proxy/defaults/main.yml

Not setting servers or redirects will result in an error when executing Ansible.
With the default, we ensure that the playbook executes without an error and (if unset) adds no server block.

Development: Initialise servers and redirects with empty array
